"""
Shapefile Health Checker — Reporter Module
==========================================
Strategy classes for rendering a :class:`~src.shapefile_health_checker.checker.HealthReport`
to a file.

Classes:
    ReportWriter    Abstract base for all report writers.
    MarkdownReporter  Renders the report as a GitHub-flavoured Markdown file.
    HtmlReporter    Renders the report as a self-contained HTML page.
"""

from __future__ import annotations

import html
from abc import ABC, abstractmethod
from pathlib import Path

from src.shapefile_health_checker.checker import CheckStatus, HealthReport


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------


class ReportWriter(ABC):
    """Abstract base for report output strategies.

    Args:
        report: The :class:`HealthReport` to render.
        output_path: File path where the rendered report will be saved.
    """

    def __init__(self, report: HealthReport, output_path: Path) -> None:
        self.report = report
        self.output_path = Path(output_path)

    @abstractmethod
    def render(self) -> str:
        """Render the report to a string in the target format.

        Returns:
            The complete rendered report as a string.
        """

    def write(self) -> None:
        """Render the report and write it to :attr:`output_path`."""
        content = self.render()
        self.output_path.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Markdown reporter
# ---------------------------------------------------------------------------


class MarkdownReporter(ReportWriter):
    """Render a :class:`HealthReport` as GitHub-flavoured Markdown."""

    def render(self) -> str:
        """Build and return the full Markdown string.

        Returns:
            A Markdown-formatted health report ready to write to a ``.md`` file.
        """
        r = self.report
        lines: list[str] = []

        # Header
        lines.append(f"# Health Report — `{r.file_path.name}`\n")
        lines.append(f"**Overall status:** {r.overall_status.name}")
        lines.append(f"**File:** `{r.file_path}`")
        lines.append(f"**CRS:** `{r.crs}`")
        lines.append(f"**Feature count:** {r.feature_count:,}")
        lines.append("")

        # Summary table
        lines.append("## Summary\n")
        lines.append("| Check | Status | Details |")
        lines.append("|-------|--------|---------|")
        for result in r.results:
            lines.append(
                f"| {result.check_name} "
                f"| {result.status_label} "
                f"| {result.details} |"
            )
        lines.append("")

        # Detailed findings for non-passing checks
        failures = [res for res in r.results if res.status != CheckStatus.PASSED]
        if failures:
            lines.append("## Detailed Findings\n")
            for res in failures:
                lines.append(f"### {res.status_label} — {res.check_name}\n")
                lines.append(f"{res.details}\n")
                if res.affected_rows:
                    row_preview = res.affected_rows[:20]
                    lines.append(
                        f"**Affected row indices** (first {len(row_preview)} shown): "
                        f"`{row_preview}`"
                    )
                lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by [GeoScriptHub — Shapefile Health Checker]"
                     "(https://github.com/matthew-lottly/GeoScriptHub)*")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML reporter
# ---------------------------------------------------------------------------


class HtmlReporter(ReportWriter):
    """Render a :class:`HealthReport` as a self-contained HTML page."""

    # Minimal inline CSS — no external dependencies
    _CSS = """
        body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
        h1 { color: #1a1a2e; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { text-align: left; padding: 0.5rem 0.75rem; border: 1px solid #ddd; }
        th { background: #f4f4f4; }
        .PASSED  { color: #2e7d32; font-weight: bold; }
        .WARNING { color: #e65100; font-weight: bold; }
        .FAILED  { color: #b71c1c; font-weight: bold; }
        .SKIPPED { color: #555; }
        .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.85rem; }
    """

    def render(self) -> str:
        """Build and return the full HTML string.

        Returns:
            A self-contained HTML page as a string.
        """
        r = self.report
        status_class = r.overall_status.name

        rows_html = ""
        for res in r.results:
            css = res.status.name
            rows_html += (
                f"<tr>"
                f"<td>{html.escape(res.check_name)}</td>"
                f"<td class='{css}'>{res.status_label}</td>"
                f"<td>{html.escape(res.details)}</td>"
                f"</tr>\n"
            )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Health Report — {html.escape(r.file_path.name)}</title>
  <style>{self._CSS}</style>
</head>
<body>
  <h1>Health Report — <code>{html.escape(r.file_path.name)}</code></h1>
  <p>
    <strong>Overall status:</strong>
    <span class="badge {status_class}">{r.overall_status.name}</span>
  </p>
  <ul>
    <li><strong>File:</strong> <code>{html.escape(str(r.file_path))}</code></li>
    <li><strong>CRS:</strong> <code>{html.escape(r.crs)}</code></li>
    <li><strong>Feature count:</strong> {r.feature_count:,}</li>
    <li><strong>Passed:</strong> {r.passed_count} / {len(r.results)}</li>
  </ul>
  <h2>Results</h2>
  <table>
    <thead><tr><th>Check</th><th>Status</th><th>Details</th></tr></thead>
    <tbody>{rows_html}</tbody>
  </table>
  <hr>
  <small>Generated by GeoScriptHub — Shapefile Health Checker</small>
</body>
</html>"""
